MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace MvcPhotoAlbum.Models
{
   public class Album
   {
       // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
      [Required]
      public  int AlbumId { get; set; }

      public virtual int UserId { get; set; }//FK
     
      [Required]
      [StringLength(30)]
      public string Title { get; set; }
    
      [DisplayFormat(DataFormatString = "{0:MM/dd/yy}", ApplyFormatInEditMode=true)]
      [Display(Name = "Date Taken")]
      public DateTime? DateTaken { get; set; }
     // public UserProfile UserName { get; set; }
      //navigation property
      public virtual ICollection< Category> Categories { get; set; }
      public virtual ICollection<Photo> Photos { get; set; }

     
     
      //adding photos to the album list
         
      //Constructor
      public Album(string albumName)
      {
         //we will create list of objects
        Photos = new List<Photo>();
       
        // Categories = new List<Category>();
         Title = albumName;

      }

      public Album()
      {

      }

      //public Album()
      //{
      //   Categories = new ICollection<Category>();
      //}
   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Models/ViewModels/AlbumViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MvcPhotoAlbum.Models;

namespace MvcPhotoAlbum.Models
{
   public class AlbumViewModel
   {
      public int AlbumId { get; set; }
      public string Title { get; set; }
      public virtual ICollection<AssignedCat> Categories { get; set; }

       
      public int? UserId { get; set; }//FK
     
      public int? CategoryId { get; set; } //FK
      //public  Photo PhotoFile  { get; set; }
     // public Category PicCategory { get; set; }
      public DateTime DateTaken { get; set; }
      public User UserName { get; set; }
      //navigation property
     // public virtual ICollection< Category> Categories { get; set; }
    
     

      public virtual ICollection<Photo> Photos { get; set; }

     
     //rivate List<Photo> photoList;
   // public virtual ICollection<Category> categories;

      //adding photos to the album list
      //public void addPhotos(string text, User theUser)
      //{
      //   Photo pic = new Photo(text);
      // Photos.Add(pic);
      //  pic.UserName = theUser;
      //}
    
      //Constructor
      public AlbumViewModel(string albumName)
      {
         //we will create list of objects
        Photos = new List<Photo>();
        // Categories = new List<Category>();
         Title = albumName;

      }

      public AlbumViewModel()
      {

      }
   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Models/ViewModels/UploadViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcPhotoAlbum.Models.ViewModels
{
   public class UploadViewModel
   {
      public int ID { get; set; }

   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcPhotoAlbum.Models;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.IO;
using MvcPhotoAlbum.Models.ViewModels;
using System.Web.Helpers;
using System.Text;
using WebMatrix.Data;
using WebMatrix.WebData;
using System.Web.Security;
using MvcPhotoAlbum.Filters;
using System.Net;





 
namespace MvcPhotoAlbum.Controllers
{
   
   [Authorize]
   [InitializeSimpleMembership]
   public class AlbumController : Controller
   {
      PhotoAlbumContext db = new PhotoAlbumContext();   
    
      [HttpGet]
      public ViewResult Index()
      {
        var i = WebSecurity.GetUserId(User.Identity.Name);
           
            var Categories = db.Categories.ToList();
         
          //  var Albums = db.Albums.ToList();
            var Albums=(from d in db.Albums where d.UserId == i select d).ToList();

            ViewBag.Categories = new SelectList(db.Categories, "CategoryId", "CategoryName");          

            return View(Albums);         
      }


      public ActionResult Search(FormCollection collection, string searchString, int? theCategoryId)
      {        
         var i = WebSecurity.GetUserId(User.Identity.Name);

         var pics = from m in db.Albums
                    where m.UserId == i
                    select m;        //all albums for logged in user

         List<Album> albumList = new List<Album>();//empty list will be returned if nothing is found 

         if (searchString == "" && theCategoryId == null)
         {
            ModelState.AddModelError("Title", "Looks like you want to find your album by name, please enter a name ");
            return View(albumList);
         }         
            else  if (theCategoryId != null)
               {
                  int CatId = Convert.ToInt32(theCategoryId);
                  ViewBag.Categories = new SelectList(db.Categories, "CategoryId", "CategoryName");
                  List<Album> myAlbumList = (from d in db.Albums where d.UserId == i select d).ToList(); //List of albums for current user
           
                  foreach (Album a in myAlbumList)//iterate through all albums for current user
                  {
                     //HashSet of all the Categories in an album
                     var albumCat = new HashSet<int>(a.Categories.Select(c => c.CategoryId));

                       if (albumCat.Contains(CatId))
                       {
                        albumList.Add(a);
                      
                       }
                   
                     }
                  return View(albumList);
                  }
               

      
              else if (!String.IsNullOrEmpty(searchString))
               {

                  pics = pics.Where(s => s.Title.Contains(searchString));//looking in the title
                  return View(pics);
                 
               }

         return View(pics);   
    }

      public ActionResult Details(int id = 0)
      {
         Album myAlbum = db.Albums.Find(id);

         if (myAlbum == null)
         {
            return HttpNotFound();
         }
         else
         {
            var photoList = (from p in db.Photos
                             where p.AlbumId == id
                             select p).ToList();

            List<Photo> foundList = new List<Photo>();

            foreach (Photo p in photoList)
            {
               if (p.Picture != null)
               {
                  foundList.Add(p);
               }
            }
            return View(foundList.ToList());
         }
      }

      /// <summary>
      /// ////////*work under this line */////
      /// </summary>
      /// <param name="id"></param>
      ///// <returns></returns>
      public ActionResult GetImage(int id)
      {
         var thePicture = db.Photos.Find(id);

         if (thePicture.Picture != null)

            return File(thePicture.Picture, "image/type");

         return null;
      }
           

      public ActionResult Create()
      {
         
         return View();//added imagemodel
      }


      //
      // POST: /Album/Create
      [HttpPost]
      public ActionResult Create(Album album)
      {
          var i = WebSecurity.GetUserId(User.Identity.Name);

         var result = (from a in db.Albums
                      where a.Title == album.Title
                      && (a.UserId == i)
                      select a);        
         try
         {            
               if (result.Count() > 0) //if I find title in table
               {
                  ModelState.AddModelError("Title", "You already have an album with that name");
                  return View();
               }

             if (album.DateTaken > DateTime.Today) //if entered date is later than todays 
               {
                  ModelState.AddModelError("DateTaken", "That's a future date!!");
                  return View();
               }                 
             
           else   if (ModelState.IsValid)
            {
                 album.UserId = i;  //user id
                  db.Albums.Add(album);
                  db.SaveChanges();    
                   return RedirectToAction("Index");
             }              

         }
         catch (DataException)
        {
           // Log the error (add a variable name after DataException)
            ModelState.AddModelError("button", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
         }
         return View();
      }


      private void PopulateAlbumCat(Album album)
      {
         var allCat = db.Categories;
         var albumCat = new HashSet<int>(album.Categories.Select(c => c.CategoryId));
         var viewModel = new List<SelectedCat>();

         foreach (var cat in allCat)//iterate thgough all categories
         {
            viewModel.Add(new SelectedCat
            {
               CategoryId = cat.CategoryId,
               CategoryName = cat.CategoryName,
               Selected = albumCat.Contains(cat.CategoryId)
            });
         }
         ViewBag.Categories = viewModel;
      }


      private void UpdateAlbumCategories(string[] checkedCategories, Album albumToUpdate)
      {
         if (checkedCategories == null)
         {
            albumToUpdate.Categories = new List<Category>();
            return;
         }
         var checkedCatHS = new HashSet<string>(checkedCategories);
         var albumCategories = new HashSet<int>(albumToUpdate.Categories.Select(c => c.CategoryId));
         foreach (var category in db.Categories)
         {
            if (checkedCatHS.Contains(category.CategoryId.ToString()))
            {
               if (!albumCategories.Contains(category.CategoryId))
               {
                  albumToUpdate.Categories.Add(category);
               }
            }
            else
            {
               if (albumCategories.Contains(category.CategoryId))
               {
                  albumToUpdate.Categories.Remove(category);
               }
            }
         }


      }


      private void AddOrUpdateCat(Album album, IEnumerable<AssignedCat> assignedCategories)
      {
         if (assignedCategories != null)
         {
            foreach (var assignedCat in assignedCategories)
            {
               if (assignedCat.Assigned)
               {
                  var category = new Category { CategoryId = assignedCat.CategoryId };
                  db.Categories.Attach(category);
                  album.Categories.Add(category);
               }

            }

         }
      }

      //GET
      public ActionResult Edit(int id)
      {
         Album album = db.Albums
         .Include(i => i.Categories)
         .Where(i => i.AlbumId == id)
         .Single();
         PopulateAlbumCat(album);

         TempData["id"] = id;
         return View(album);

      }



      [HttpPost]
      public ActionResult Edit(int id, FormCollection formCollection, string[] SelectedCat)
      {//Album album,

         var albumToUpdate = db.Albums
            .Include(t => t.Categories)
             .Single(t => t.AlbumId == id);

         if (TryUpdateModel(albumToUpdate, "", null, new string[] { "Categories" }))
         //if (TryUpdateModel(albumToUpdate, "", new string[] { "Albums" }))
         {
            try
            {
               UpdateAlbumCategories(SelectedCat, albumToUpdate);

               db.Entry(albumToUpdate).State = EntityState.Modified;
               db.SaveChanges();
               TempData["id"] = id;
               return RedirectToAction("Index");//,new
               // { 
               //    albumId = albumToUpdate.AlbumId });
               // }
            }
            catch (DataException)
            {
               ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator");
            }
         }

         PopulateAlbumCat(albumToUpdate);
         TempData["id"] = id;
         // return View(albumToUpdate);
         return View("Index");

      }


      [HttpGet]
      public ActionResult Upload(int id)
      {
       
            Album album = db.Albums
            .Include(i => i.Categories)
            .Where(i => i.AlbumId == id)
            .Single();

            return View(album);
   
       
      }

    
      

      [HttpPost]
      public ActionResult Upload(HttpPostedFileBase file, int id, string description)
      {
         var albumToUpdate = db.Albums
            .Single(t => t.AlbumId == id);      //album     

         if (file != null && file.ContentLength > 0)
         {
            string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".JPG" };

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Create.cshtml
@model MvcPhotoAlbum.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Album</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
            @Html.ValidationMessage("Title")
            @Html.HiddenFor(model => model.Title)
        </div>

          <div class="editor-label">
            @Html.LabelFor(model => model.DateTaken)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTaken)
            @Html.ValidationMessageFor(model => model.DateTaken)
        @* @Html.ValidationMessage("DateTaken")*@
        </div>
        
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Delete.cshtml
@model MvcPhotoAlbum.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

    
    
<h3>Are you sure you want to delete this?</h3>
  <fieldset>  
   <legend>Album </legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
      <div>
          @Html.DisplayFor(model => model.Title)
      </div>
   

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateTaken)
    </div>
      
    <div class="display-field">
        @Html.DisplayFor(model => model.DateTaken)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/DeletePicture.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "DeletePicture";
}

<h2>DeletePicture</h2>
 
    
<h3>Are you sure you want to delete this Picture?</h3><br />
  
 <fieldset>  
   <legend>Album </legend>

      <img src="/Album/GetImage/@Html.Encode(Model.PhotoId)"  style=" width: auto; height : 300px;" alt="Picture" />
   
</fieldset>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> 
        
          @Html.ActionLink("Back to List", "Details/",new{id=Model.AlbumId})
        

    </p>

}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Details.cshtml
@model IEnumerable<MvcPhotoAlbum.Models.Photo>

@{
    ViewBag.Title = "Display";
}   

@Styles.Render("~/Content/themes/base/css")


<h2>Pictures</h2>
 

    
<table> 
     
@foreach (var item in Model) {
  <tr id="myImage">
      <td >
      <img src="/Album/GetImage/@Html.Encode(item.PhotoId)"  style=" width: auto; height : 300px;" alt="Picture" />.
      @Html.Hidden(item.PhotoId.ToString())
       </td>

      <td>
     @Html.DisplayFor(modelItem  =>item.Description)
     </td>

     <td >
    

       @Html.Hidden(item.PhotoId.ToString())
        
          @Ajax.ActionLink("Delete", "DeletePicture", new { id = item.PhotoId },
                                                                 new AjaxOptions
                                                                     {
                                                                       
                                                                         Confirm = "Are you sure you want to delete this picture?",
                                                                         HttpMethod = "DELETE",
                                                                         UpdateTargetId = "myImage",
                                                                         OnSuccess = "onPhotoDeleteSuccess",
                                                                         OnFailure = "onProductDeleteFailure"
                                                                     }
                                                                     )

     
   
     </td>   
</tr>
}
   
    </table>

  

     
 @*   

@section scripts
{
     
    @Scripts.Render("~/bundles/jqueryui")

     

     @Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    // Callback function that is invoked when our Delete operation succeeds
    function onPhotoDeleteSuccess(response, status, data)
    {
        
        var id = "#PhotoId" + response.id;
        $(id).remove();
    }

    function onProductDeleteFailure(context)
    {
        alert("Something went horribly wrong");
    }

    function adjustURL(context)
    {
        var request = context.get_request();
        var url = request.get_url();
        request.set_url(url);

    }
 </script>
    
         }

       *@

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Edit.cshtml
@model MvcPhotoAlbum.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Album</legend>

@*        
<p>
          @Html.ActionLink("Upload Pictures", "Upload",Model.AlbumId)
   
</p>
      *@ 
            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.AlbumId)
      
       

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.DateTaken)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTaken)
            @Html.ValidationMessageFor(model => model.DateTaken)
        </div>

      
    </fieldset>
    
    
    <div class="editor-label">
            @Html.Label("Categories")
        </div>
    
    <div class="editor-field">
          <table>
            <tr>
                @{
    int cnt = 0;
    List<MvcPhotoAlbum.Models.SelectedCat> categories = ViewBag.Categories;
    foreach (var category in categories)
    {
        if (cnt++ % 4 == 0)
        {
            @:</tr><tr>
         }
         @:<td>
            <input type="checkbox"
           name  ="selectedCat"
          value="@category.CategoryId"
          @(Html.Raw(category.Selected ? "checked=\"checked\"" : "")) />
          @category.CategoryName
          @:</td>
                }
            @:</tr>
                }
        </table>
        </div>

    
         <p>
            <input type="submit" value="Edit" />
        </p>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Index.cshtml
@model IEnumerable<MvcPhotoAlbum.Models.Album>

@{
    ViewBag.Title = "My Albums";
}
@Styles.Render("~/Content/themes/base/css")
 <script type="text/javascript">

            function selectedIndexChanged() {

            }

        </script>
<h2>My Albums</h2>


@Ajax.ActionLink("ajax load for id: 101", "IndexData", new {id = 101}, 
new AjaxOptions {
    HttpMethod = "Get",
    InsertionMode = InsertionMode.Replace, 
    OnSuccess = "SuccessFunction",
    UpdateTargetId = "myDiv"})
   
<div id="myDiv"></div>
<div id="myDiv2" style="border-width: medium; border-color: black"></div>

 @{Html.BeginForm("Search", "Album", FormMethod.Post); 
   
   <table>
   <tr>
       <td>
              @Html.Label("Search album  name  or Category")   
      </td>
       <td>
   
        
      </td>
  </tr>
       <tr>
          <td>
             <input type="text" name="searchString" />
             
         @Html.DropDownList("theCategoryId",ViewBag.Categories as SelectList, "Category")
         <input type="submit" value="Search" />
           </td>
           <td>

           
   </tr>
          </table> 
      
                }
                      

            
<table>

    <tr>
       <td>

    @Html.ActionLink(" Create New ", "Create")       
    
   
        </td>
       

        <td>
 
        </td>

          <td>
         
    
        </td>
    </tr> 
</table>



<table>
     
    <tr>
       
      <th></th>
        <th>

            @Html.DisplayNameFor(model => model.Title)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AlbumId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AlbumId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AlbumId }) |               
            @Html.ActionLink("Upload", "Upload", new { id = item.AlbumId })
        </td>
        <td>
           @* @Html.DisplayFor(modelItem => item.Title)*@
             @Html.ActionLink(Convert.ToString(item.Title),"Details",new { id = item.AlbumId })
        </td>
       @* <td>
            @Html.DisplayFor(modelItem => item.UserName.Name)
        </td>*@
       
        <td>
            @Html.DisplayFor(modelItem => item.DateTaken)
        </td>
        
    </tr>
}

</table>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/PartialDelete.cshtml
@model IEnumerable<MvcPhotoAlbum.Models.Photo>


<h2> my view</h2>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/PartialUpload.cshtml
@model MvcPhotoAlbum.Models.Photo

<h1>Hello from partial view</h1>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Search.cshtml
@model IEnumerable<MvcPhotoAlbum.Models.Album>


@if (Model.Count() > 0 )
{
    ViewBag.Title = "Search";
<h2>Results</h2>
}
else
{
<div><strong> No results were found</strong></div>
}





    
  @foreach (var item in Model)
    {
       <table>
           <tr>
               <td>
           @Html.LabelFor(modelItem => item.Title)
              </td>
               <td>
            @Html.LabelFor(modelItem => item.DateTaken)
               </td>
           </tr>
           <tr>
               <td>
             @Html.ActionLink(Convert.ToString(item.Title),"Details",new { id = item.AlbumId })
                </td>
               <td>
             @Html.DisplayFor(modelItem => item.DateTaken)
               </td>
            </tr>
          </table>
    }

   

 @* @Html.DisplayFor(modelItem => item.Title)*@

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/SearchIndex.cshtml
@model IEnumerable<MvcPhotoAlbum.Models.Album>

@{
    ViewBag.Title = "SearchIndex";
}

<h2>SearchIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTaken)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTaken)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AlbumId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AlbumId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AlbumId })
        </td>
    </tr>
}

</table>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Thumbnail.cshtml
@model MvcPhotoAlbum.Models.Album

@{
    ViewBag.Title = "Thumbnail";
}

<h2>Thumbnail</h2>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Album/Upload.cshtml
@model MvcPhotoAlbum.Models.Album
<h2>Upload Your Photos</h2>

@{
    ViewBag.Title = "Upload Your Photos";
   
}
<script type="text/javascript">
   function getFile()
 {
    document.getElementById("upfile").click();
   }

    function sub(obj)
    {
        var file = obj.value;
        var fileName = file.split("\\");
        document.getElementById("yourBtn").innerHTML = fileName[fileName.length - 1];
        document.myForm.submit();       
   //     event.preventDefault();
    }

</script>
<br />
<br />


    @using (Html.BeginForm("Upload", "Album", FormMethod.Post, new { enctype = "multipart/form-data", name="myForm" }))
    {
        
    @Html.ValidationSummary();
      
     <h4>
          
         @Html.DisplayFor(model => model.Title)
         @Html.ValidationMessage("Title")
      </h4>
         
        
     
  

  <div id="yourBtn" style='float:left; font-size:1.1em; -webkit-border-radius: 5px; -moz-border-radius: 5px; width: 150px;  
                           height:35px;  background-color:#ffffff; border: 1px solid #BBB; cursor:pointer;'  onclick="getFile()"> 
            Click to upload!

  </div>
                   
<!-- this is your file input tag, so i hide it!-->
   <div style="height: 0px;width: 0px;  float:left; overflow:hidden;">

   <input id="upfile"  class="file" name="file" type="file" value="upload" />
   
    </div>    
 
        <!--Description textbox !-->
    <input id="Desription" style='float:left;' name="Description" type="text" value="Description" /> 
      
        
     <input   type="submit" style='float:left;'  value="Upload and Save" />    
    @* <input type="submit" style=" padding-left:10px;  " id="txtSubmit" value="Save" />*@
        
    <div class="field-validation-error" id="spanfile"></div> 
       
    }


<!-- I could've use   this to upload automatically    without submoit button    onchange="sub(this)"  !-->