MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Xml.Linq;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace MvcPhotoAlbum.Models
{
   public class Photo
   {
      [Required ]
      [FileExtensions(Extensions="jpg,png")]
      [UIHint("Image")]
      public string FileName { get; set; }
     
      public int PhotoId { get; set; }
      public virtual int AlbumId { get; set; }//FK
      public byte[] Picture { get; set; }//testing 
      public virtual string Description { get; set; }
  

      //constructor
      public Photo(string file)
      {
         FileName = file;
      }

      public Photo()
      {


      }

   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Models/ViewModels/UploadViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcPhotoAlbum.Models.ViewModels
{
   public class UploadViewModel
   {
      public int ID { get; set; }

   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MvcPhotoAlbum.Models;
using MvcPhotoAlbum.Models.ViewModels;
using System.Web.Helpers;



namespace MvcPhotoAlbum.Controllers
{
   [Authorize(Roles = "Admin")]
   public class PhotoController : Controller
   {
      private PhotoAlbumContext db = new PhotoAlbumContext();
      //

      [HttpGet]
      public ViewResult Index()
      {
        

         return View();
      }

   }
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Create.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Photo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FileName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FileName)
            @Html.ValidationMessageFor(model => model.FileName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Delete.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Photo</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FileName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FileName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Details.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Photo</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FileName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FileName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.PhotoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Edit.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Photo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FileName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FileName)
            @Html.ValidationMessageFor(model => model.FileName)
        </div>

        @Html.HiddenFor(model => model.PhotoId)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Index.cshtml
@model MvcPhotoAlbum.Models.Photo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@{
    ViewBag.Title = "Upload";
}

<h2>  This view can only be accessed by Admin /h2>

   

MvcPhotoAlbum/MvcPhotoAlbum/MvcPhotoAlbum/Views/Photo/Upload.cshtml
@model MvcPhotoAlbum.Models.Photo  

<h2>Upload Your Photos</h2>

@{
    ViewBag.Title = "Upload";
   
}

<h2>Upload Photos</h2>

@*@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

@*<form method="post" enctype="multipart/form-data">*@
    @using (Html.BeginForm("Upload", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    @Html.ValidationSummary();
      
        
      
         @FileUpload.GetHtml(initialNumberOfFiles:1, allowMoreFilesToBeAdded:true, includeFormTag:false,addText:"Add Files",
         uploadText:"Upload File")
            @Html.DisplayFor( x => x.FileName)
          // @Html.HiddenFor(model => model.AlbumId)
       
  
      
       
    <ol>
    <li class="lifile">
    @*<input type="file" id="fileToUpload" name="file" />*@
    <span class="field-validation-error" id="spanfile"></span>
    </li>
    </ol>
    <input type="submit" id="btnSubmit" value="Upload" />
    }


<div>
    @Html.ActionLink("Back to List", "Index", "UploadImage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}